services:
  - type: web
    name: stampa-etichette
    env: python3

    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py collectstatic --noinput

    startCommand: |
     python manage.py migrate --noinput
     gunicorn print_label.wsgi:application --bind 0.0.0.0:${PORT}

    envVars:
      - key: DB_PATH
        value: /var/data/db.sqlite3
      - key: DEBUG
        value: "False"

    disks:
      - name: data
        mountPath: /var/data
        sizeGB: 1
